require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WebProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # WebProject. As you add validations to WebProject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all web_projects as @web_projects" do
      web_project = WebProject.create! valid_attributes
      get :index
      assigns(:web_projects).should eq([web_project])
    end
  end

  describe "GET show" do
    it "assigns the requested web_project as @web_project" do
      web_project = WebProject.create! valid_attributes
      get :show, :id => web_project.id
      assigns(:web_project).should eq(web_project)
    end
  end

  describe "GET new" do
    it "assigns a new web_project as @web_project" do
      get :new
      assigns(:web_project).should be_a_new(WebProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested web_project as @web_project" do
      web_project = WebProject.create! valid_attributes
      get :edit, :id => web_project.id
      assigns(:web_project).should eq(web_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WebProject" do
        expect {
          post :create, :web_project => valid_attributes
        }.to change(WebProject, :count).by(1)
      end

      it "assigns a newly created web_project as @web_project" do
        post :create, :web_project => valid_attributes
        assigns(:web_project).should be_a(WebProject)
        assigns(:web_project).should be_persisted
      end

      it "redirects to the created web_project" do
        post :create, :web_project => valid_attributes
        response.should redirect_to(WebProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved web_project as @web_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        WebProject.any_instance.stub(:save).and_return(false)
        post :create, :web_project => {}
        assigns(:web_project).should be_a_new(WebProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WebProject.any_instance.stub(:save).and_return(false)
        post :create, :web_project => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested web_project" do
        web_project = WebProject.create! valid_attributes
        # Assuming there are no other web_projects in the database, this
        # specifies that the WebProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WebProject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => web_project.id, :web_project => {'these' => 'params'}
      end

      it "assigns the requested web_project as @web_project" do
        web_project = WebProject.create! valid_attributes
        put :update, :id => web_project.id, :web_project => valid_attributes
        assigns(:web_project).should eq(web_project)
      end

      it "redirects to the web_project" do
        web_project = WebProject.create! valid_attributes
        put :update, :id => web_project.id, :web_project => valid_attributes
        response.should redirect_to(web_project)
      end
    end

    describe "with invalid params" do
      it "assigns the web_project as @web_project" do
        web_project = WebProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WebProject.any_instance.stub(:save).and_return(false)
        put :update, :id => web_project.id, :web_project => {}
        assigns(:web_project).should eq(web_project)
      end

      it "re-renders the 'edit' template" do
        web_project = WebProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WebProject.any_instance.stub(:save).and_return(false)
        put :update, :id => web_project.id, :web_project => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested web_project" do
      web_project = WebProject.create! valid_attributes
      expect {
        delete :destroy, :id => web_project.id
      }.to change(WebProject, :count).by(-1)
    end

    it "redirects to the web_projects list" do
      web_project = WebProject.create! valid_attributes
      delete :destroy, :id => web_project.id
      response.should redirect_to(web_projects_url)
    end
  end

end
